[project]
name = "meshage"
version = "0.1.0"
description = "Send and receives meshtastic messages via MQTT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiomqtt>=2.4.0",
    "asphalt>=4.12.0",
    "cryptography>=45.0.5",
    "meshtastic>=2.7.0",
]
