name: Publish Release

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv sync --group test
      - name: Run tests
        run: uv run pytest
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv sync --no-dev
      - name: Create package
        run: |
          uv build
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: dist/meshage-*.whl
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/meshage
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Create release draft
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: true
          fail_on_unmatched_files: true
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1

